### ISSUE TITLE
Its not available on the `crates.io` registry.

### ISSUE THREAD

**Issue by shawnscode** [Herschel/swf-rs#2]
Hi, Herschel

This crate looks great, but i just found out that its not available on the `crates.io` registry. Could you fix this? Thanks a lot.

**Comment by hydroper** [comment]
Not sure if you know it, but you can've Git dependencies:
```
[dependencies]
swf-rs = { git = 'https://github.com/Herschel/swf-rs' }
```

**Comment by shawnscode** [comment]
Yes, that do works. But i might not be able to publish my little ui framework, since `Cargo` just rejects all the publish requests with external dependencies.

**Comment by Herschel** [comment]
I have been meaning to publish this to crates.io! I will try to do it within a week. Thank you for the kind words!

**Comment by Herschel** [comment]
Sorry for the very long delay on this one! It is now available on crates.io. Contributions welcome!
